from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from .lookup import LookupResult, query_domains
from .presets import list_presets, load_domain_file, load_preset
from .speed import measure_tcp_latency, pick_best_ipv4, pick_fastest_ipv4


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="dns-query",
        description="Query public DNS / DoH servers for domain IPs. Useful for generating hosts entries.",
    )
    parser.add_argument("domains", nargs="*", help="Domain names, e.g. github.com")
    parser.add_argument(
        "--preset",
        help=f"Built-in domain list. Available: {', '.join(list_presets()) or 'none'}",
    )
    parser.add_argument(
        "--from-file",
        type=Path,
        help="Read domains from a text file (one per line)",
    )
    parser.add_argument(
        "--dns",
        action="append",
        dest="dns_servers",
        metavar="IP",
        help="Use a specific DNS server (repeatable). Default: Cloudflare/Google/Quad9/AliDNS/DNSPod/OpenDNS",
    )
    parser.add_argument("--no-doh", action="store_true", help="Skip DNS-over-HTTPS fallback")
    parser.add_argument("--ipv4-only", action="store_true", help="Query A records only")
    parser.add_argument("--timeout", type=float, default=3.0, help="Per-resolver timeout in seconds")
    parser.add_argument(
        "--workers",
        type=int,
        default=8,
        metavar="N",
        help="Parallel domain queries when resolving many names (default: 8)",
    )
    parser.add_argument(
        "--fast",
        action="store_true",
        help="Fast mode: fewer resolvers, skip DoH, stop after first useful answer",
    )
    parser.add_argument(
        "--fastest",
        action="store_true",
        help="TCP-connect to :443 and rank IPv4 addresses by handshake time",
    )
    parser.add_argument(
        "--format",
        choices=("table", "hosts", "json"),
        default="table",
        help="Output format",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Write hosts/json output to a file instead of stdout",
    )
    return parser


def collect_domains(args: argparse.Namespace) -> list[str]:
    domains: list[str] = []
    seen: set[str] = set()

    def add(items: list[str]) -> None:
        for item in items:
            domain = item.strip().lower().rstrip(".")
            if domain and domain not in seen:
                seen.add(domain)
                domains.append(domain)

    add(args.domains)
    if args.preset:
        add(load_preset(args.preset))
    if args.from_file:
        add(load_domain_file(args.from_file))
    return domains


def choose_ip(result: LookupResult, fastest: bool, probes: int = 3) -> str | None:
    if fastest:
        pick = pick_best_ipv4(result.ipv4, probes=probes)
        return pick.ip if pick else None
    if result.ipv4:
        return result.ipv4[0]
    if result.ipv6:
        return result.ipv6[0]
    return None


def render_table(results: list[LookupResult], fastest: bool) -> str:
    lines = [f"{'domain':<42} {'ip':<40} {'sources'}"]
    lines.append("-" * 110)
    for result in results:
        if not result.ips:
            lines.append(f"{result.domain:<42} {'(unresolved)':<40}")
            continue

        ranked = result.ipv4 + result.ipv6
        if fastest and result.ipv4:
            samples = measure_tcp_latency(result.ipv4)
            ranked = [sample.ip for sample in samples] + result.ipv6
            latency = {sample.ip: sample.latency_ms for sample in samples}
        else:
            latency = {}

        sources_by_ip: dict[str, list[str]] = {}
        for hit in result.hits:
            sources_by_ip.setdefault(hit.ip, [])
            if hit.source not in sources_by_ip[hit.ip]:
                sources_by_ip[hit.ip].append(hit.source)

        for ip in ranked:
            extra = ""
            if ip in latency:
                extra = (
                    f"  {latency[ip]:.0f} ms"
                    if latency[ip] is not None
                    else "  timeout"
                )
            source = ",".join(sources_by_ip.get(ip, []))
            lines.append(f"{result.domain:<42} {ip:<40} {source}{extra}")
    return "\n".join(lines) + "\n"


def render_hosts(results: list[LookupResult], fastest: bool) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Generated by dns-query at {stamp}",
        "# Review before merging into /etc/hosts. Re-query periodically; CDN IPs change.",
        "",
    ]
    missing: list[str] = []
    for result in results:
        ip = choose_ip(result, fastest=fastest)
        if ip:
            lines.append(f"{ip:<20} {result.domain}")
        else:
            missing.append(result.domain)
    if missing:
        lines.append("")
        lines.append("# unresolved: " + ", ".join(missing))
    return "\n".join(lines) + "\n"


def render_json(results: list[LookupResult], fastest: bool) -> str:
    payload = []
    for result in results:
        item = {
            "domain": result.domain,
            "ipv4": result.ipv4,
            "ipv6": result.ipv6,
            "sources": [
                {"ip": hit.ip, "type": hit.record_type, "source": hit.source}
                for hit in result.hits
            ],
            "errors": result.errors,
        }
        if fastest and result.ipv4:
            item["latency_ms"] = {
                sample.ip: None if sample.latency_ms is None else round(sample.latency_ms, 1)
                for sample in measure_tcp_latency(result.ipv4)
            }
            item["fastest_ipv4"] = pick_fastest_ipv4(result.ipv4)
        payload.append(item)
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] in {"apply", "preview", "remove", "restore", "status"}:
        from .apply import main as apply_main

        return apply_main(argv)

    args = build_parser().parse_args(argv)
    try:
        domains = collect_domains(args)
    except FileNotFoundError as exc:
        print(exc, file=sys.stderr)
        return 2

    if not domains:
        build_parser().print_help()
        return 2

    record_types = ("A",) if args.ipv4_only else ("A", "AAAA")
    results = query_domains(
        domains,
        dns_servers=args.dns_servers,
        use_doh=not args.no_doh,
        record_types=record_types,
        timeout=args.timeout,
        domain_workers=max(1, args.workers),
        fast=args.fast,
    )

    if args.format == "hosts":
        text = render_hosts(results, fastest=args.fastest)
    elif args.format == "json":
        text = render_json(results, fastest=args.fastest)
    else:
        text = render_table(results, fastest=args.fastest)

    if args.output:
        args.output.write_text(text, encoding="utf-8")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(text)

    unresolved = sum(1 for result in results if not result.ips)
    return 1 if unresolved else 0
